'use client';
import { FormEvent, useState } from 'react';
import { site } from '@/lib/site';
import Icon from '@/components/ui/Icon';
const initial = { name: '', phone: '', email: '', organization: '', service: '', date: '', guests: '', message: '' };
export default function BriefForm() {
  const [data, setData] = useState(initial); const [status, setStatus] = useState(''); const [preview, setPreview] = useState('');
  function update(key: keyof typeof initial, value: string) { setData(current => ({ ...current, [key]: value })); setStatus(''); }
  function build() { return `CHỦ ĐỀ: Trao đổi ý tưởng sự kiện\n\nHọ tên: ${data.name}\nĐiện thoại: ${data.phone}\nEmail: ${data.email}\nĐơn vị: ${data.organization}\nNhu cầu: ${data.service}\nThời gian dự kiến: ${data.date}\nSố lượng khách: ${data.guests}\n\nMô tả ý tưởng:\n${data.message}`; }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!data.name || !data.phone || !data.service) { setStatus('Vui lòng điền họ tên, điện thoại và nhu cầu để tiếp tục.'); return; } const body = build(); window.location.href = `mailto:${site.email}?subject=${encodeURIComponent('Trao đổi ý tưởng sự kiện')}&body=${encodeURIComponent(body)}`; setStatus('Ứng dụng email của bạn đang được mở. Bạn có thể sao chép brief nếu cần.'); setPreview(body); }
  async function copyBrief() { const body = build(); setPreview(body); try { await navigator.clipboard.writeText(body); setStatus('Đã sao chép nội dung brief.'); } catch { setStatus('Nội dung brief đã hiện bên dưới để bạn sao chép.'); } }
  return <form className="brief-form" onSubmit={submit}><h2>Chia sẻ ý tưởng của bạn</h2><p>Điền những điều bạn đã biết. Các thông tin chưa chắc chắn có thể để trống.</p><div className="form-grid"><label className="field">Họ và tên *<input required value={data.name} onChange={e => update('name', e.target.value)} autoComplete="name" /></label><label className="field">Số điện thoại *<input required type="tel" value={data.phone} onChange={e => update('phone', e.target.value)} autoComplete="tel" /></label><label className="field">Email<input type="email" value={data.email} onChange={e => update('email', e.target.value)} autoComplete="email" /></label><label className="field">Đơn vị / tổ chức<input value={data.organization} onChange={e => update('organization', e.target.value)} /></label><label className="field">Nhu cầu *<select required value={data.service} onChange={e => update('service', e.target.value)}><option value="">Chọn một nhu cầu</option><option>Tổ chức sự kiện thể thao</option><option>Sự kiện doanh nghiệp</option><option>Giáo dục thể thao</option><option>Thiết bị sự kiện</option><option>Truyền thông / thiết kế</option><option>Khác</option></select></label><label className="field">Thời gian dự kiến<input value={data.date} onChange={e => update('date', e.target.value)} placeholder="Ví dụ: Tháng 12/2026" /></label><label className="field">Số lượng khách<input value={data.guests} onChange={e => update('guests', e.target.value)} placeholder="Ví dụ: khoảng 300 người" /></label><label className="field field-full">Điều bạn muốn tạo nên<textarea value={data.message} onChange={e => update('message', e.target.value)} placeholder="Mục tiêu, địa điểm, điều bạn mong muốn..." /></label></div><div className="form-actions"><button className="button button-red" type="submit">Soạn email gửi Your Dreams <Icon name="up-right" /></button><button className="button button-outline" type="button" onClick={copyBrief}>Sao chép brief</button></div><p className="form-note">Biểu mẫu không lưu dữ liệu trên website. Khi gửi, thông tin được mở trong ứng dụng email của bạn.</p>{status && <p className="form-status" role="status">{status}</p>}{preview && <pre className="brief-preview">{preview}</pre>}</form>;
}
