export type LegacyContentRoute = {
  sourceSlug: string;
  kind: 'post' | 'project';
  contentSlug: string;
  canonicalSlug: string;
};

export const legacyContentRoutes: LegacyContentRoute[] = [
  {"sourceSlug":"to-chuc-su-kien-chuyen-nghiep","kind":"post","contentSlug":"to-chuc-su-kien-chuyen-nghiep","canonicalSlug":"to-chuc-su-kien-chuyen-nghiep"},
  {"sourceSlug":"dich-vu-to-chuc-giai-boi","kind":"post","contentSlug":"to-chuc-giai-boi-cho-doanh-nghiep","canonicalSlug":"to-chuc-giai-boi-cho-doanh-nghiep"},
  {"sourceSlug":"dich-vu-to-chuc-giai-chay-tron-goi","kind":"post","contentSlug":"to-chuc-su-kien-chuyen-nghiep","canonicalSlug":"to-chuc-su-kien-chuyen-nghiep"},
  {"sourceSlug":"dich-vu-to-chuc-giai-bong-da","kind":"post","contentSlug":"to-chuc-su-kien-chuyen-nghiep","canonicalSlug":"to-chuc-su-kien-chuyen-nghiep"},
  {"sourceSlug":"dich-vu-to-chuc-giai-pickleball","kind":"post","contentSlug":"to-chuc-giai-pickleball","canonicalSlug":"dich-vu-to-chuc-giai-pickleball"},
  {"sourceSlug":"to-chuc-kinh-ngu-quan-bien","kind":"project","contentSlug":"kinh-ngu-quan-bien-ocean-city-2023","canonicalSlug":"to-chuc-kinh-ngu-quan-bien"},
  {"sourceSlug":"lop-boi-khu-do-thi","kind":"post","contentSlug":"to-chuc-giai-boi-cho-doanh-nghiep","canonicalSlug":"to-chuc-giai-boi-cho-doanh-nghiep"},
  {"sourceSlug":"to-chuc-lop-boi-doanh-nghiep","kind":"post","contentSlug":"to-chuc-giai-boi-cho-doanh-nghiep","canonicalSlug":"to-chuc-giai-boi-cho-doanh-nghiep"},
  {"sourceSlug":"huong-dan-to-chuc-lop-pickleball","kind":"post","contentSlug":"to-chuc-giai-pickleball","canonicalSlug":"dich-vu-to-chuc-giai-pickleball"},
  {"sourceSlug":"huong-dan-to-chuc-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"huong-dan-to-chuc-su-kien-khanh-thanh","kind":"post","contentSlug":"to-chuc-su-kien-khai-truong","canonicalSlug":"to-chuc-su-kien-khai-truong"},
  {"sourceSlug":"top-cong-ty-to-chuc-su-kien","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"to-chuc-su-kien-hoi-thao","kind":"post","contentSlug":"to-chuc-su-kien-doanh-nghiep","canonicalSlug":"to-chuc-su-kien-hoi-thao"},
  {"sourceSlug":"bao-gia-to-chuc-su-kien-tron-goi","kind":"post","contentSlug":"chi-phi-to-chuc-su-kien","canonicalSlug":"bao-gia-to-chuc-su-kien-tron-goi"},
  {"sourceSlug":"top-trung-tam-to-chuc-su-kien","kind":"post","contentSlug":"chon-dia-diem-to-chuc-su-kien-ha-noi","canonicalSlug":"top-trung-tam-su-kien-ha-noi"},
  {"sourceSlug":"to-chuc-su-kien-teambuilding","kind":"post","contentSlug":"to-chuc-su-kien-doanh-nghiep","canonicalSlug":"to-chuc-su-kien-hoi-thao"},
  {"sourceSlug":"dich-vu-to-chuc-su-kien","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"top-cong-ty-su-kien-uy-tin","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"cong-ty-su-kien-chuyen-nghiep","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"chuoi-su-kien-di-de-lon","kind":"project","contentSlug":"di-de-lon-rox-living-2025","canonicalSlug":"chuoi-su-kien-di-de-lon"},
  {"sourceSlug":"huong-dan-thue-ban-ghe-su-kien","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"quy-trinh-to-chuc-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"to-chuc-su-kien-khai-truong","kind":"post","contentSlug":"to-chuc-su-kien-khai-truong","canonicalSlug":"to-chuc-su-kien-khai-truong"},
  {"sourceSlug":"cam-nang-nha-bat-su-kien","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"to-chuc-khai-truong-cua-hang","kind":"post","contentSlug":"to-chuc-su-kien-khai-truong","canonicalSlug":"to-chuc-su-kien-khai-truong"},
  {"sourceSlug":"ke-hoach-to-chuc-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"cam-nang-nhan-vien-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"tuyen-dung-to-chuc-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"to-chuc-su-kien-1-6","kind":"post","contentSlug":"to-chuc-su-kien-theo-mua","canonicalSlug":"to-chuc-su-kien-1-6"},
  {"sourceSlug":"huong-dan-quan-ly-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"chay-su-kien-thanh-cong","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"top-trung-tam-su-kien-ha-noi","kind":"post","contentSlug":"chon-dia-diem-to-chuc-su-kien-ha-noi","canonicalSlug":"top-trung-tam-su-kien-ha-noi"},
  {"sourceSlug":"cho-thue-nha-bat-su-kien","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"to-chuc-su-kien-tuyen-dung-hieu-qua","kind":"post","contentSlug":"to-chuc-su-kien-tuyen-dung","canonicalSlug":"to-chuc-su-kien-tuyen-dung-hieu-qua"},
  {"sourceSlug":"cong-ty-su-kien-kien-vang","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"cong-ty-to-chuc-su-kien-ha-noi","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"to-chuc-su-kien-ha-noi","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"cong-ty-event-chuyen-nghiep","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"dia-diem-to-chuc-su-kien-ha-noi","kind":"post","contentSlug":"chon-dia-diem-to-chuc-su-kien-ha-noi","canonicalSlug":"top-trung-tam-su-kien-ha-noi"},
  {"sourceSlug":"tuyen-dung-nhan-vien-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"huong-dan-chuyen-vien-to-chuc-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"cam-nang-to-chuc-su-kien-ngoai-troi","kind":"post","contentSlug":"to-chuc-su-kien-ngoai-troi","canonicalSlug":"cam-nang-to-chuc-su-kien-ngoai-troi"},
  {"sourceSlug":"viec-lam-to-chuc-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"cong-ty-to-chuc-su-kien-chuyen-nghiep","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"nha-to-chuc-su-kien-chuyen-nghiep","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"cam-nang-su-kien-ngoai-troi","kind":"post","contentSlug":"to-chuc-su-kien-ngoai-troi","canonicalSlug":"cam-nang-to-chuc-su-kien-ngoai-troi"},
  {"sourceSlug":"bao-gia-cho-thue-thiet-bi-su-kien","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"top-don-vi-to-chuc-su-kien","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"huong-dan-san-khau-su-kien","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"to-chuc-su-kien-khai-truong-2","kind":"post","contentSlug":"to-chuc-su-kien-khai-truong","canonicalSlug":"to-chuc-su-kien-khai-truong"},
  {"sourceSlug":"huong-dan-to-chuc-event","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"dich-vu-to-chuc-su-kien-chuyen-nghiep","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"cong-ty-to-chuc-su-kien","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"lap-ke-hoach-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"ky-nang-to-chuc-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"dich-vu-to-chuc-su-kien-ha-noi","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"to-chuc-su-kien-tieng-anh","kind":"post","contentSlug":"to-chuc-su-kien-bang-tieng-anh","canonicalSlug":"to-chuc-su-kien-tieng-anh"},
  {"sourceSlug":"to-chuc-su-kien-trung-thu","kind":"post","contentSlug":"to-chuc-su-kien-theo-mua","canonicalSlug":"to-chuc-su-kien-1-6"},
  {"sourceSlug":"agency-to-chuc-su-kien-a-z","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"cam-nang-thiet-bi-su-kien","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"huong-dan-thue-bat-su-kien","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"nhan-vien-su-kien-khong-kinh-nghiem","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"trung-tam-su-kien-ha-noi","kind":"post","contentSlug":"chon-dia-diem-to-chuc-su-kien-ha-noi","canonicalSlug":"top-trung-tam-su-kien-ha-noi"},
  {"sourceSlug":"huong-dan-so-do-to-chuc-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"to-chuc-su-kien-chuyen-nghiep-2","kind":"post","contentSlug":"to-chuc-su-kien-chuyen-nghiep","canonicalSlug":"to-chuc-su-kien-chuyen-nghiep"},
  {"sourceSlug":"truyen-thong-to-chuc-su-kien","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"y-tuong-to-chuc-su-kien-doc-dao","kind":"post","contentSlug":"y-tuong-to-chuc-su-kien","canonicalSlug":"y-tuong-to-chuc-su-kien-doc-dao"},
  {"sourceSlug":"huong-dan-chay-su-kien-part-time","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"nhan-vien-chay-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"thue-thiet-bi-su-kien-chuyen-nghiep","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"huong-dan-ke-hoach-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"to-chuc-su-kien-sinh-nhat","kind":"post","contentSlug":"to-chuc-su-kien-sinh-nhat","canonicalSlug":"to-chuc-su-kien-sinh-nhat"},
  {"sourceSlug":"thue-do-su-kien-tron-goi","kind":"post","contentSlug":"cam-nang-thue-thiet-bi-su-kien","canonicalSlug":"cam-nang-thiet-bi-su-kien"},
  {"sourceSlug":"cam-nang-agency-su-kien","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"cam-nang-event-su-kien","kind":"post","contentSlug":"event-la-gi-va-cac-loai-su-kien","canonicalSlug":"cam-nang-event-su-kien"},
  {"sourceSlug":"huong-dan-lam-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"tong-quan-su-kien-event","kind":"post","contentSlug":"event-la-gi-va-cac-loai-su-kien","canonicalSlug":"cam-nang-event-su-kien"},
  {"sourceSlug":"cong-ty-su-kien-tuyen-dung","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"khach-san-to-chuc-su-kien-ha-noi","kind":"post","contentSlug":"chon-dia-diem-to-chuc-su-kien-ha-noi","canonicalSlug":"top-trung-tam-su-kien-ha-noi"},
  {"sourceSlug":"tuyen-dung-thuc-tap-sinh-to-chuc-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"vi-tri-to-chuc-su-kien","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"cong-ty-to-chuc-su-kien-ha-noi-2","kind":"post","contentSlug":"chon-don-vi-to-chuc-su-kien","canonicalSlug":"cong-ty-su-kien-chuyen-nghiep"},
  {"sourceSlug":"tuyen-dung-nhan-vien-su-kien-2","kind":"post","contentSlug":"nghe-to-chuc-su-kien","canonicalSlug":"cam-nang-nhan-vien-su-kien"},
  {"sourceSlug":"chon-khong-gian-to-chuc-su-kien","kind":"post","contentSlug":"chon-dia-diem-to-chuc-su-kien-ha-noi","canonicalSlug":"top-trung-tam-su-kien-ha-noi"},
  {"sourceSlug":"huong-dan-quan-ly-to-chuc-su-kien","kind":"post","contentSlug":"checklist-lap-ke-hoach-su-kien","canonicalSlug":"ke-hoach-to-chuc-su-kien"},
  {"sourceSlug":"to-chuc-giai-boi-cho-doanh-nghiep","kind":"post","contentSlug":"to-chuc-giai-boi-cho-doanh-nghiep","canonicalSlug":"to-chuc-giai-boi-cho-doanh-nghiep"},
  {"sourceSlug":"nang-tam-phong-trao-pickleball-huong-dan-toan-dien-de-to-chuc-lop-hoc-chuyen-nghiep","kind":"post","contentSlug":"to-chuc-giai-pickleball","canonicalSlug":"dich-vu-to-chuc-giai-pickleball"},
];

export const canonicalLegacySlugByPostSlug: Record<string, string> = {
  'to-chuc-su-kien-chuyen-nghiep': 'to-chuc-su-kien-chuyen-nghiep',
  'chon-don-vi-to-chuc-su-kien': 'cong-ty-su-kien-chuyen-nghiep',
  'chi-phi-to-chuc-su-kien': 'bao-gia-to-chuc-su-kien-tron-goi',
  'chon-dia-diem-to-chuc-su-kien-ha-noi': 'top-trung-tam-su-kien-ha-noi',
  'cam-nang-thue-thiet-bi-su-kien': 'cam-nang-thiet-bi-su-kien',
  'to-chuc-su-kien-doanh-nghiep': 'to-chuc-su-kien-hoi-thao',
  'to-chuc-su-kien-theo-mua': 'to-chuc-su-kien-1-6',
  'to-chuc-su-kien-ngoai-troi': 'cam-nang-to-chuc-su-kien-ngoai-troi',
  'y-tuong-to-chuc-su-kien': 'y-tuong-to-chuc-su-kien-doc-dao',
  'event-la-gi-va-cac-loai-su-kien': 'cam-nang-event-su-kien',
  'nghe-to-chuc-su-kien': 'cam-nang-nhan-vien-su-kien',
  'to-chuc-su-kien-tuyen-dung': 'to-chuc-su-kien-tuyen-dung-hieu-qua',
  'to-chuc-su-kien-bang-tieng-anh': 'to-chuc-su-kien-tieng-anh',
  'to-chuc-giai-pickleball': 'dich-vu-to-chuc-giai-pickleball',
  'to-chuc-giai-boi-cho-doanh-nghiep': 'to-chuc-giai-boi-cho-doanh-nghiep',
  'to-chuc-su-kien-khai-truong': 'to-chuc-su-kien-khai-truong',
  'to-chuc-su-kien-sinh-nhat': 'to-chuc-su-kien-sinh-nhat',
  'checklist-lap-ke-hoach-su-kien': 'ke-hoach-to-chuc-su-kien',
};

export function postHref(postSlug: string) {
  const legacySlug = canonicalLegacySlugByPostSlug[postSlug];
  return legacySlug ? `/${legacySlug}` : `/blog/${postSlug}`;
}

export function projectHref(projectSlug: string) {
  const legacyRoute = legacyContentRoutes.find(route => route.kind === 'project' && route.contentSlug === projectSlug);
  return legacyRoute ? `/${legacyRoute.canonicalSlug}` : `/du-an/${projectSlug}`;
}
