import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Breadcrumbs from '@/components/ui/Breadcrumbs';
import Icon from '@/components/ui/Icon';
import { pageMetadata } from '@/lib/seo';
import { site } from '@/lib/site';
export const metadata: Metadata = pageMetadata('Về Your Dreams', 'Tìm hiểu Công ty Cổ phần Your Dreams: định hướng, cách làm và các lĩnh vực hoạt động trong sự kiện, thể thao, giáo dục.', '/gioi-thieu');
const values = [['Chỉn chu', 'Từng chi tiết được chuẩn bị để cùng phục vụ trải nghiệm chung.'], ['Sáng tạo', 'Mỗi chương trình bắt đầu từ bối cảnh riêng, không từ một khuôn mẫu.'], ['Tận tâm', 'Cùng khách hàng đi từ ý tưởng đến khi chương trình khép lại.']];
export default function AboutPage() { return <><div className="container"><Breadcrumbs items={[{ name: 'Về chúng tôi', href: '/gioi-thieu' }]} /><header className="page-intro"><p className="eyebrow">VỀ YOUR DREAMS</p><h1>Từ ý tưởng đến<br /><span className="red-text">sự kiện hoàn hảo.</span></h1><p>Your Dreams là Công ty Cổ phần hoạt động trong tổ chức sự kiện, giáo dục thể thao và các hoạt động trải nghiệm. Chúng tôi tạo điều kiện để con người gặp gỡ, vận động và cùng nhớ về một khoảnh khắc có ý nghĩa.</p></header></div><section className="page-section"><div className="container two-column"><div className="detail-image"><Image src="/images/di-de-lon.webp" alt="Đội ngũ và trẻ em trong chương trình Đi để lớn ROX Living 2025" fill sizes="(max-width: 760px) 100vw, 45vw" /></div><div className="prose"><h2>Chúng tôi tin vào sức mạnh của trải nghiệm.</h2><p>Một chương trình chỉ thật sự trọn vẹn khi mục tiêu của đơn vị tổ chức được chuyển thành trải nghiệm dễ cảm nhận cho người tham gia. Vì vậy, chúng tôi không bắt đầu bằng danh sách thiết bị hay một mẫu kịch bản có sẵn.</p><p>Đội ngũ bắt đầu bằng việc lắng nghe: ai sẽ đến, điều gì cần được tạo nên, không gian có những điều kiện nào. Từ đó, ý tưởng, nội dung, nhân sự và vận hành được kết nối thành một kế hoạch.</p><p>Your Dreams cũng phát triển hoạt động giáo dục thể thao qua Swim For Life Việt Nam, tạo cơ hội học tập và vận động cho trẻ em, gia đình và cộng đồng.</p><Link href="/lien-he" className="button button-red">Cùng trao đổi ý tưởng <Icon name="up-right" /></Link></div></div></section><section className="section services-section"><div className="container"><p className="eyebrow">CÁCH CHÚNG TÔI LÀM VIỆC</p><h2 className="related-heading">Những giá trị dẫn đường.</h2><div className="value-grid">{values.map(([title, text], i) => <div key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section><section className="section"><div className="container two-column"><div className="prose"><p className="eyebrow red-text">THÔNG TIN DOANH NGHIỆP</p><h2>Minh bạch để cùng tin tưởng.</h2><p>Đây là những thông tin chính thức được ghi nhận trong hồ sơ năng lực của Your Dreams. Thông tin dự án và dịch vụ được cập nhật theo phạm vi hợp tác thực tế.</p></div><aside className="legal-info"><h2>{site.company}</h2><dl><dt>Mã số thuế</dt><dd>{site.taxId}</dd><dt>Thành lập</dt><dd>27/08/2019</dd><dt>Đại diện</dt><dd>Nguyễn Huy Mạnh</dd><dt>Địa chỉ</dt><dd>{site.address}</dd><dt>Hotline</dt><dd><a href={site.phoneLink}>{site.phone}</a></dd><dt>Email</dt><dd><a href={`mailto:${site.email}`}>{site.email}</a></dd></dl></aside></div></section></>; }
